#!/bin/bash

echo starting
exec 2>&1
set -eux
eval "export HOME=~$( id -un )"
export PATH="$HOME/bin:$PATH"

cd "$( git rev-parse --show-toplevel )"

export DRY_RUN=
export TAIL=true
export TIDY=

exec ./with-live node ./dist/src/main.js
